### ISSUE TITLE
problem with google protobuf

### ISSUE THREAD

**Issue by JoshWolper** [electronicarts/pbmpm#1]
Probably just my own inexperience with ruby, any help you could provide would be much appreciated ^_^ I'm on MacOS Monterey 12.0.1 for reference~

Upon running jekyll serve --livereload, I'm getting the following errors related to google protobuf. I found [this](https://stackoverflow.com/questions/74959406/github-pages-installation-jekyll-v-output-require-cannot-load-such-file) thread and tried the marked answer of uninstalling and installing google protobuf but it led to a different error :( I'll put the second error below the first error
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- google/protobuf_c (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/protobuf_c (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/2.6/protobuf_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/2.6/protobuf_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/protobuf_c.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/2.6/protobuf_c.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/google-protobuf-3.23.4-x86_64-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
Then after uninstalling and installing google protobuf getting this error
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find google-protobuf-3.23.4 in any of the sources (Bundler::GemNotFound)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler.rb:107:in `setup'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by chlewin** [comment]
Hello Josh, I'm afraid I didn't run into that problem when trying this on MacOS, although I did have to reinstall Ruby using this tutorial: https://jekyllrb.com/docs/installation/macos/

After that it worked first time.

**Comment by JoshWolper** [comment]
Reinstalling ruby worked!! Thanks so much for the quick response, this project is soooo impressive. Awesome work 🤩
